### ISSUE TITLE
Enhancement: Mac Support

### ISSUE THREAD

**Issue by ILuvGemz** [nebulazorua/andromeda-engine#1]
## What is your suggestion, and why should it be implemented?

I suggest Mac support since it would be more convenient for Mac users. I had a friend who uses Mac, and they said they couldn’t compile the current code. So I suggest Mac support could be friendly for my friend and others who use Mac.

**Comment by nebulazorua** [comment]
Yea I **do** want to make some stuff windows-only so that macs can compile, but I'll need to get a mac VM or somethin' along those lines to help with debugging all that

**Comment by ILuvGemz** [comment]
Alright then,  I’ll look forward to your development from here on. I’m gonna look for other engines for the time being since I also can’t understand reading the modcharting sequence. The main reason that I got interest with this engine is that I heard it can change the note speed.

I couldn’t find a how to (or I could’ve missed it) on the charting, so I wasn’t able to understand the processes of the engine.

**Comment by ILuvGemz** [comment]
> Alright then, I’ll look forward to your development from here on. I’m gonna look for other engines for the time being since I also can’t understand reading the modcharting sequence. The main reason that I got interest with this engine is that I heard it can change the note speed.
> 
> I couldn’t find a how to (or I could’ve missed it) on charting the markers and modcharting, so I wasn’t able to understand the processes of the engine.

**Comment by polybiusproxy** [comment]
> Yea I **do** want to make some stuff windows-only so that macs can compile, but I'll need to get a mac VM or somethin' along those lines to help with debugging all that

heard of github actions? you dont need a mac vm
actions is like a ci
