### ISSUE TITLE
how to fix this???

### ISSUE THREAD

**Issue by guisende** [nebulazorua/andromeda-engine#117]
this error

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:357: characters 17-18 : hscript.Error has no field e
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:373: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:379: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:384: characters 70-74 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:388: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:392: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:396: characters 69-73 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:71: characters 52-56 : hscript.Error has no field line
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/PolymodScriptClass.hx:74: characters 87-91 : hscript.Error has no field line

**Comment by MemeHoovy** [comment]
`haxelib install polymod 1.4.3`

**Comment by guisende** [comment]
![image](https://user-images.githubusercontent.com/88600361/196236180-fcf139e8-bc2f-452c-81a9-a794a28a0f16.png)


this happened

**Comment by MemeHoovy** [comment]
again **use the old version of polymod** `haxelib install polymod 1.4.3`

**Comment by guisende** [comment]
omg thx <333 
helped me a lot
thx

**Comment by MemeHoovy** [comment]
np
