### ISSUE TITLE
Crash Error: Old Menu Option

### ISSUE THREAD

**Issue by Capeletini** [nebulazorua/andromeda-engine#13]
**_I was testing andromeda engine on windows, using the most recent version up to date 8/16, and was researching the options. I noticed an option called "Old Menu", I activated it and the game closed. I try to open it again but it keeps closing, the configuration of the options are saved automatically and now I have no way to change it

I would like to receive help in this since I am very excited to finally have access to this engine and that I cannot use it makes me sad_**

**Comment by nebulazorua** [comment]
fixed
