### ISSUE TITLE
Bug Report: please fix this 

### ISSUE THREAD

**Issue by gummybear17** [nebulazorua/andromeda-engine#14]
please fix this please 
source/PlayState.hx:209: characters 10-15 : Type not found : LuaVM
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:37: characters 46-58 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:1122: characters 41-53 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:289: characters 38-50 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:867: characters 35-47 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/StoryMenuState.hx:332: characters 14-27 : Class<PlayState> has no field campaignScore
source/Character.hx:207: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/LuaClass.hx:157: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:166: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:167: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:208: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:219: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:227: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:225: characters 21-29 : Field Register is declared 'override' but doesn't override any field
source/LuaClass.hx:1217: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1230: characters 12-17 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1251: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1276: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:1278: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:1281: characters 22-31 : Unknown identifier : className
source/LuaClass.hx:1317: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:1315: characters 21-29 : Field Register is declared 'override' but doesn't override any field
source/Note.hx:91: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/Note.hx:139: characters 71-84 : Class<PlayState> has no field getSVFromTime
source/Note.hx:156: characters 66-77 : Class<PlayState> has no field getFNFSpeed

**Comment by gummybear17** [comment]
and im on mac

**Comment by nebulazorua** [comment]
mac doesnt work rn
