### ISSUE TITLE
Very large error

### ISSUE THREAD

**Issue by thedirptastic** [nebulazorua/andromeda-engine#16]
the source code is super broken on mac with countless errors. plz fix this.

source/PlayState.hx:209: characters 10-15 : Type not found : LuaVM
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:37: characters 46-58 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:1122: characters 41-53 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:289: characters 38-50 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/LuaClass.hx:867: characters 35-47 : Type not found : StatePointer
source/StoryMenuState.hx:24: lines 24-467 : Defined in this class
source/StoryMenuState.hx:332: characters 14-27 : Class<PlayState> has no field campaignScore
source/Character.hx:207: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/LuaClass.hx:157: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:166: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:167: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:208: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:219: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:227: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:225: characters 21-29 : Field Register is declared 'override' but doesn't override any field
source/LuaClass.hx:1217: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1230: characters 12-17 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1251: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1276: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:1278: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:1281: characters 22-31 : Unknown identifier : className
source/LuaClass.hx:1317: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:1315: characters 21-29 : Field Register is declared 'override' but doesn't override any field
source/NoteGraphic.hx:35: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/NoteGraphic.hx:84: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/NoteGraphic.hx:95: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/Note.hx:184: characters 71-84 : Class<PlayState> has no field getSVFromTime
source/Note.hx:202: characters 66-77 : Class<PlayState> has no field getFNFSpeed
/usr/local/lib/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
/usr/local/lib/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

**Comment by nebulazorua** [comment]
workin' on it
