### ISSUE TITLE
Bug Report: Markers not working in chart editor

### ISSUE THREAD

**Issue by ILuvGemz** [nebulazorua/andromeda-engine#2]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

#### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
Andromeda Engine B6.
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
I have tried to use the new marker feature in the chart editor, but for odd reasons, when I use the stepper, it threw me a Null Object Reference. I hope this could be fixed.

**Comment by nebulazorua** [comment]
It's bugged in the release build iirc, but if you compile it manually it SHOULD work fine?

You also need to place the marker THEN use the stepper, I should probably make that more obvious and not crash if you don't have a marker selected
