### ISSUE TITLE
Question: How can I use the option to change speed? And how can I change the startup speed?

### ISSUE THREAD

**Issue by Capeletini** [nebulazorua/andromeda-engine#23]
How can I use the option to change speed? And how can I change the startup speed?
I don't really understand how to use it

**Comment by nebulazorua** [comment]
Press M to place a 'marker', this is used to denote the scroll speed. The regular chart scroll speed determines the starting speed. Once you've placed a marker, use the marker tab in the charter and change the number. The number is a modifier for the speed, so 2 is 2x the normal scrollspeed
