### ISSUE TITLE
Bug Report: WHAT IS THIS?

### ISSUE THREAD

**Issue by TON-Games** [nebulazorua/andromeda-engine#26]
when I build the game it looks like this:

source/LuaClass.hx:37: characters 46-58 : Type not found : StatePointer
source/StoryMenuState.hx:21: lines 21-446 : Defined in this class
source/LuaClass.hx:1122: characters 41-53 : Type not found : StatePointer
source/StoryMenuState.hx:21: lines 21-446 : Defined in this class
source/LuaClass.hx:289: characters 38-50 : Type not found : StatePointer
source/StoryMenuState.hx:21: lines 21-446 : Defined in this class
source/LuaClass.hx:867: characters 35-47 : Type not found : StatePointer
source/StoryMenuState.hx:21: lines 21-446 : Defined in this class
source/LuaClass.hx:157: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:166: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:167: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:208: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:219: characters 16-21 : Class<llua.LuaL> has no field error
source/LuaClass.hx:227: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:225: characters 21-29 : Field Register is declared 'override' but doesn't override any field
source/LuaClass.hx:1217: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1230: characters 12-17 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1251: characters 14-19 : Class<llua.LuaL> has no field error
source/LuaClass.hx:1276: characters 5-12 : LuaClass does not have a constructor
source/LuaClass.hx:1278: characters 5-14 : Unknown identifier : className
source/LuaClass.hx:1281: characters 22-31 : Unknown identifier : className
source/LuaClass.hx:1317: characters 11-19 : LuaClass has no field Register
source/LuaClass.hx:1315: characters 21-29 : Field Register is declared 'override' but doesn't override any field
C:/HaxeToolkit/haxe/lib/hxvm-luajit/git/src/vm/lua/LuaVM.hx:56: characters 7-37 : Bool should be Int
C:/HaxeToolkit/haxe/lib/hxvm-luajit/git/src/vm/lua/LuaVM.hx:62: characters 11-16 : Class<llua.LuaL> has no field error
source/PlayState.hx:1162: characters 19-62 : LuaSprite does not have a constructor
source/PlayState.hx:1207: characters 25-44 : LuaNote does not have a constructor
source/PlayState.hx:1208: characters 25-44 : LuaNote does not have a constructor
source/PlayState.hx:1209: characters 23-42 : LuaNote does not have a constructor
source/PlayState.hx:1210: characters 26-45 : LuaNote does not have a constructor
source/PlayState.hx:1212: characters 22-42 : LuaNote does not have a constructor
source/PlayState.hx:1213: characters 22-42 : LuaNote does not have a constructor
source/PlayState.hx:1214: characters 20-40 : LuaNote does not have a constructor
source/PlayState.hx:1215: characters 23-43 : LuaNote does not have a constructor
source/PlayState.hx:1219: characters 12-49 : LuaCharacter does not have a constructor
source/PlayState.hx:1220: characters 12-42 : LuaCharacter does not have a constructor
source/PlayState.hx:1221: characters 13-45 : LuaCharacter does not have a constructor
source/PlayState.hx:1223: characters 17-52 : LuaSprite does not have a constructor
source/PlayState.hx:1224: characters 18-53 : LuaSprite does not have a constructor
source/PlayState.hx:1228: characters 21-54 : LuaCam does not have a constructor
source/PlayState.hx:1229: characters 20-47 : LuaCam does not have a constructor
source/PlayState.hx:1231: characters 7-15 : LuaClass has no field Register
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

**Comment by TheGamingCat89** [comment]
try updating luajit or whatever its called

**Comment by CM333** [comment]
I'm having aa similar issue myself, checking if I accidentally got the unstable version.

**Comment by nebulazorua** [comment]
Remove and reinstall hxvm-luajit and linc_luajit
