### ISSUE TITLE
Question: How to add crossfades

### ISSUE THREAD

**Issue by IndigoDarkw0lf** [nebulazorua/andromeda-engine#30]
## What is your question?

I saw [this video](https://www.youtube.com/watch?v=0rVP_eUbQKs) and I wanted to know how to code in the crossfades. I know the remake was cancelled because of the removal of mid fight masses. I was trying to code it in myself, but to no avail.

**Comment by TheGamingCat89** [comment]
Look at the mfm remake source code

**Comment by IndigoDarkw0lf** [comment]
> Look at the mfm remake source code

i forgot to close this when i saw the source code, but thanks!
