### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by funnyman4** [nebulazorua/andromeda-engine#31]
**### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.**
Windows 10 x86.
**## What version of the game are you using? Look in the bottom left corner of the main menu.**
Cant get due to bug, says 7B in MainMenuState.hx.
**## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.**
Nope.
**## Please describe your issue. Provide extensive detail and images if possible.**
Game crashes on compile, error is Null Object Reference, no code changes.
![null png](https://user-images.githubusercontent.com/88360172/133909317-6e8209ca-dd16-4208-9050-7f513b934709.jpg)

**Comment by CM333** [comment]
what was the solution, if i may ask?
