### ISSUE TITLE
Bug Report: Lua issue

### ISSUE THREAD

**Issue by TheGamingCat89** [nebulazorua/andromeda-engine#32]
I've seen people having issues with this in Kade Engine but I was trying to download andromeda and got a very similar error
![image](https://user-images.githubusercontent.com/81439207/134819861-f3feac3b-5a69-4d18-be13-81b002a079f8.png)
No one seems to know how to fix it and I had not seen this before either
This issue happens with Beta 6 only by the way

**Comment by jukru89** [comment]
same :/ dont know how to fix it

**Comment by TheGamingCat89** [comment]
> same :/ dont know how to fix it

I found a fix

haxelib remove linc_luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git 0af04cd3a1
