### ISSUE TITLE
Null Object Reference

### ISSUE THREAD

**Issue by PineappleCake99** [nebulazorua/andromeda-engine#35]
When i try to build the source code, it builds fine, but when the program opens it gives me a error saying "null object reference". I dont know how do i fix this.

**Comment by Tutorialing** [comment]
remove polymod from project.xml.

**Comment by Jonnycatmeow** [comment]
it give off this error because idk why but the new one is kinda bad use mine for that error  
https://github.com/Jonnycatmeow/old-polymod.git

**Comment by nebulazorua** [comment]
fixed
