### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by IdioticX** [nebulazorua/andromeda-engine#40]
Andromeda Engine Problem.
When I finally compile Andromeda, I get this dumb error. It is a textbox message with the words "Null Object Reference." After I click on the textbox, the game crashes. How do I fix the error? Image:
![image](https://user-images.githubusercontent.com/93747739/140439864-5c69cb35-c319-4d73-a6cb-04ad33facd5d.png)

**Comment by AfkBotPloudos** [comment]
Recent polymod version is broken,which is why you're having this problem
type these into cmd:
haxelib remove polymod
haxelib git polymod https://github.com/larsiusprime/polymod bb5f0a1

**Comment by nebulazorua** [comment]
fixed
