### ISSUE TITLE
Bug Report: when i tried to build i got this 

### ISSUE THREAD

**Issue by Jonnycatmeow** [nebulazorua/andromeda-engine#44]
source/PlayState.hx:154: characters 10-15 : Type not found : LuaVM
source/StoryMenuState.hx:24: lines 24-467 : ... Defined in this class
source/StoryMenuState.hx:332: characters 14-27 : Class<PlayState> has no field campaignScore
source/Character.hx:207: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/LuaClass.hx:1088: characters 29-51 : PlayState has no field swapCharacterByLuaName
source/NoteGraphic.hx:35: characters 46-57 : Class<PlayState> has no field daPixelZoom
source/NoteGraphic.hx:84: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/NoteGraphic.hx:95: characters 45-56 : Class<PlayState> has no field daPixelZoom
source/Note.hx:187: characters 18-31 : Class<PlayState> has no field getSVFromTime
source/Note.hx:205: characters 66-77 : Class<PlayState> has no field getFNFSpeed
source/Receptor.hx:49: characters 51-62 : Class<PlayState> has no field daPixelZoom

**Comment by nebulazorua** [comment]
try running  
`haxelib remove linc_luajit
haxelib remove hxvm-luajit
haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit`

into command prompt

**Comment by Jonnycatmeow** [comment]
also 
i know how to fix your linc_luajit
