### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by kjonaas** [nebulazorua/andromeda-engine#5]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
N/A
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
N/A
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 10, latest version
## What version of the game are you using? Look in the bottom left corner of the main menu.
Andromeda B6 (latest release)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Starting up Week 6 will cause this issue instantly.
## Please describe your issue. Provide extensive detail and images if possible.
Upon starting up week 6 via the Story Mode menu on Hard mode, the game crashes and returns an error "Null Object Reference" (Video at https://streamable.com/iy3ydv)

**Comment by nebulazorua** [comment]
try turning off week 6 shaders in options > preferences > effects and get back to me

**Comment by nebulazorua** [comment]
wait nvm
i got it lmao

**Comment by kjonaas** [comment]
It actually is happening with all weeks, I just tried to play week 6 first when I downloaded it. Same issue occurs in freeplay.
