### ISSUE TITLE
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cacheBug Report: 

### ISSUE THREAD

**Issue by ScooterSmash0** [nebulazorua/andromeda-engine#57]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/FlixelBackend.hx:50: characters 25-30 : openfl.utils.IAssetCache has no field cache

How to fix that?

**Comment by ThatDisabledKid** [comment]
fixed it  
https://github.com/ThatDisabledKid/polymod

**Comment by nebulazorua** [comment]
fixed
