### ISSUE TITLE
Bug Report: Charting issues.

### ISSUE THREAD

**Issue by ILuvGemz** [nebulazorua/andromeda-engine#62]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
x86_64

## Please describe your issue. Provide extensive detail and images if possible.

Every time I pressed 7 on a song, which takes me to the charter, I always had this error where instead of starting from section 0, it starts on a random number. Additionally, I couldn’t go back to the previous sections after I passed the number.

And here’s another thing about markers, they don’t work AT ALL. when I placed a marker on the current github build, instead of slowing down the notes, all the notes after the marker went missing, and when I came back and deleted the markers, the game works fine again! Is there an issue?

These are issues that I am unable to fix and those I’m practically confused it happened to say the least. Anyways, please fix it.

**Comment by nebulazorua** [comment]
its not a random number, it starts you from where you were in the song.. Or atleast, it should?
It's likely just the chart itself being fucked. BPM Changes messing with it, maybe?

**Comment by ILuvGemz** [comment]
Found the issue. Check latest pull rq.
