### ISSUE TITLE
Question: eXecYtaBl pLIZ

### ISSUE THREAD

**Issue by juanroman74454811** [nebulazorua/andromeda-engine#63]
wY ISnT thEr eXecUTaBLe!1!1!1!!!

**Comment by CalibriLight** [comment]
Compile yourself

**Comment by juanroman74454811** [comment]
> Compile yourself

![Quote](https://user-images.githubusercontent.com/92176733/154063749-4ae6ecca-2b81-4d47-9d90-521857f44e5b.png)
i̷̢̤̜̪̤̦̥̓̾̊̑̈͂̇̂̽̚ ̴̡̢̳̻̣̞͓͎̝̟̤̱͙̠̓̓̅̈́̚͝ͅẁ̸̯̫͒̌̏̉̋͒̕̕͝i̵̝̹͋̅͘ĺ̸̛̗̤̮̭͉͍͈̦̝̹͛̀̅̅͜l̵̛̲̃̒͊͒͛̿͊͗͗̔̋͝͝ ̶͓̽̅k̸̭̙̮̜̜̣̇í̸̡̢͎͖̑ḷ̴͎͕͖̰̬͐͛̋͋̑̿͘͘l̷̢͔̮̦̬̙̖̭͕̳̂̈́̏͊́́̇͊́̎ͅ ̵̹͔͇̱̻͔̻͉̇̈́̒̀̐͑͋̎̉̄͠y̷̧͈̻͈͖͚̭̫̥̙͎̼̍ͅọ̵͙͔̾̐͌̈́̒͌̍̃̚̚̚͠͝͝͠ũ̶̧̡̪̦͉̀̌̈́ ̷̞̝̯̲̺͓̣̊̀͒̓̇̉͐̕͝͝i̷͕̗͇̒̉́̑͐̉̽̈̅͑͝f̶̢̬̗̣̮̭͙̲̼͍̺͛̕ ̵̰͍͔̯̘̫̤͊̆̾̓̀̊̏̈́̄̿͆͑̚͝ỳ̵̤̠̱͉̣̪̯̥̤̩͂́͌͌̈́̂̃̆̆̈͘ȯ̶̧̧̯̤̈́͊͛̆̇͒̃u̶͇̲̗̟̖̙͗̂͜͜ ̵̡̧̻̟̔͊̐͂̒̾̀͌͛̇̕͝ḏ̸̡̛̟̟͉̣͇̭̊͆̊͂̆͑̄̈̕ȏ̴̧̫͚̠͍̰̗̜̙͂̿̈́̄̄n̷͎̉͑̊̽̄͐̍̆̚̚t̵͙̭͔͆̀̅̕ͅ ̴̡̧͍̝̮̫͈̬̂̎̐̈́͜͝ͅg̷̥̈̉̏́̓̄͘͝ḭ̸͈̤̯̯̤̗̰̺͈̟̆̃v̵̢̨͓̤̖͇͖̯́̓̿ͅͅe̷̢͇̳̪̩̳̥̯̫͍͚͗̇̓̀̑̒̾͂̈͂̐͆̕̚ ̸̧̱̗͙͔͖͑̀̊͌̎͌́̌͂̽̔̒͘͝͠m̴̡̨̨͙̲̼̟̲̖̌͌̉̎͒͋͜ȩ̸̤͇̲̪̹͇̞̥̞̤̬̒͐̐̓̅͠͝ͅ ̴̨͉̬̻͓̭̐̏a̸̻̤͔̫̠̿̈̋́̌͐́̓̐ͅ ̸̫̳̈́̃̑͗̀̒̔͒͋̚̕p̶̠̩͍͓̖̹͓͌͑̔̎̉͜ͅṙ̷̛͓͕̮̩͓̬̩͒͗͑͐́̂͋̌̃͂́͐̔͜e̸̛͓̗̋̽̅͌́̆̋͂̽͛́͌͊͘ ̵̤̇̂̎͜ć̶̛͍͗̈́̄͂̚̕͘͠o̵̡̮̬̟̟̣̬̞̖̖̐͑̔͂̍̃͘m̵̢̢̦̖̪̻͖̮̜̘̖͎̤̅͛͐̔̂̐̎̍̓͝͠͝ͅp̸͉̌͂ï̴̌̓̐̏͌͑̌̿̚͜͠͠l̴̙͔̭̜̻̰̻͇͚̥͂̎̿͗̒̓͊̀͆̉͑̇̓̑̉ͅe̵̹̦͚̞̠͇̦͈̓̋ͅd̷͚̜̣̮̘̯͎̻̞̫̪͍͉̉̿͌̈́̊̑͛̋͆́̄̚͝ͅ ̴̧̛̹̫͇̰̪̟͆̈͐̂̈̇̀̔͘͝͝v̶̭̙̗̤͚̘̎͆͗̏̊̍̽̆̓́͝ę̸̡̖͕̳̯͔̻͎̬͙̹̟̘́́̈́̚͠͠r̶̨̛͖̤̗̰̬͕͔̭̠͓̼͍̗͆́̇̈́̾̓̉͑̇̑̐͘͠s̸͕̳̘͚̞̳̞͔̩͔͋̓͆̔͆́̋́̽̌ǐ̵̪̆̃͐͂̔ơ̶̛̗̬̼͓̳̝̪̦͙͕͕͇̞͈̔n̵̢̪̻͎̻̫͓̼̠̙̖̼͛͋̋͆͋̏̅ ̷͕̖͐͌́̓̽͌̋o̴̫͙̞̘͉͙͍̪̤͑̈́̅͊̉͆͊̎̂͐̃͐̃f̴̮̖̥͔̱͚̣̲͖͔͇̲̌́̋͒͑̅̅̍̿̌̌̍͝͠ ̷̢̩̗͇̙͚̹̬͚͔̻̜͇̜͎͊̍̿͋͐ṱ̷̛̈́̑͂̎̓̅̈́̑̓̿̋͝͝ḩ̶̡̭͓̹͇̘̺͕̭͚͙̂͂́̈́̆̀̀̂̈ͅi̷̧͓̹͕̻̫̼̗͉̭̲̦̭̯͙̽̾͐̋͌̍͐͂͘̚͝͝ṡ̶͕̔̂͌͛̉̃͒̕ ̵̤̊ẹ̴̡̘̟̗̫͎̹̜̺͉͎͙́̿ņ̸͔͚̹̘̤̺̯̄̇̈̿̄̄̀̇̃̅̅͋͂͝͝ͅg̵̞̰̯̭̓̓͛̄̅̄͆͛̌̉͘̕͠i̶̢̥̥̎̐̔͗̓ń̴͔̯̙͇͕̬̱̺͔̬̏͒̉͋̐͐̈́̀͗ȩ̷̡̪̣͔̠͉̫̙͙̊̄́͆̑͂̌͘
