### ISSUE TITLE
Bug Report: a problem with polymod i think

### ISSUE THREAD

**Issue by jukru89** [nebulazorua/andromeda-engine#67]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData)
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:483: characters 80-81 : Missing ;
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:483: characters 80-81 : For function argument 'message'
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:494: characters 82-83 : Missing ;
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/Polymod.hx:494: characters 82-83 : For function argument 'message'

can someone tell me how to fix this?

**Comment by nebulazorua** [comment]
fixed
