### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by malipali** [nebulazorua/andromeda-engine#69]
First time compile. Everything has been installed (I checked it 3 times). I get the following errors:
source/LuaClass.hx:27: characters 8-18 : Type not found : llua.Macro
source/LuaClass.hx:51: characters 46-58 : Type not found : StatePointer
source/CoolUtil.hx:17: lines 17-139 : ... Defined in this class
source/LuaClass.hx:2085: characters 41-53 : Type not found : StatePointer
What should I do? Is this a me problem, or is it just a matter of unfinished code?

**Comment by malipali** [comment]
nice
![image](https://user-images.githubusercontent.com/51425055/153740525-4f5e0e82-8a81-4366-8f6d-e35be83b8554.png)

**Comment by nebulazorua** [comment]
It's in the readme
![image](https://user-images.githubusercontent.com/12458328/153744657-20a7f4b8-b10f-46f7-b171-96fc294d2355.png)

**Comment by malipali** [comment]
and now I have this
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20:`` characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData)`
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys`
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys`
`C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or Iterable`
