### ISSUE TITLE
Compilation Issue Part 2

### ISSUE THREAD

**Issue by malipali** [nebulazorua/andromeda-engine#71]
Last advice worked, but now I have a new error wall:
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:20: characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData)
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys
C:/HaxeToolkit/haxe/lib/polymod/1,4,2/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

What should I do with polymod?

**Comment by nebulazorua** [comment]
fixed
