### ISSUE TITLE
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData) C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or IterableBug Report: 

### ISSUE THREAD

**Issue by kellptic7** [nebulazorua/andromeda-engine#72]
why is this on my screeen and how tf do i fix it

C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 35-48 : openfl.utils.IAssetCache has no field getBitmapKeys (Suggestion: getBitmapData)
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:20: characters 15-50 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 35-46 : openfl.utils.IAssetCache has no field getFontKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:24: characters 15-48 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 35-47 : openfl.utils.IAssetCache has no field getSoundKeys
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/backends/OpenFLBackend.hx:28: characters 15-49 : You can't iterate on a Dynamic value, please specify Iterator or Iterable

![image](https://user-images.githubusercontent.com/96875257/153783562-c6a5ccee-c545-4589-8ade-397bd4f03e9c.png)

**Comment by Snoni** [comment]
delete `<haxelib name="polymod"/>` in project.xml
tgt v3  doesnt even use it
and that means andromeda doesnt either

**Comment by nebulazorua** [comment]
fixed
