### ISSUE TITLE
A strange bug

### ISSUE THREAD

**Issue by AnonymousPerson10112** [nebulazorua/andromeda-engine#77]
Hi, just wondering how to compile my stuff correctly because everything i try it says this

![image](https://user-images.githubusercontent.com/100014521/154789760-fb3b038a-c490-4f14-b177-684dfcc70343.png)

just wondering how to fix this, thanks!

**Comment by beeanie** [comment]
just do `lime build windows` thats how you build it

**Comment by womenarecringe** [comment]
i have the same problem, and "lime build windows" just makes the same error show up

**Comment by nebulazorua** [comment]
Update to haxe 4.2.4
