### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by Theinkyslayer** [nebulazorua/andromeda-engine#82]
whenever i try to compile it just says this:

source/states/PlayState.hx:563: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/states/CharacterEditorState.hx:258: characters 5-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/LuaClass.hx:42: characters 56-58 : Abstract haxe.ds.Map has no @:to function that accepts haxe.IMap<Any, LuaClass>

and yes i tried the
haxelib remove linc_luajit
haxelib remove hxvm-luajit
method, but it still did not work

**Comment by nebulazorua** [comment]
Update to haxe 4.2.4
