### ISSUE TITLE
Bug Report: compiling issue

### ISSUE THREAD

**Issue by jukru89** [nebulazorua/andromeda-engine#83]
source/states/PlayState.hx:566: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/states/CharacterEditorState.hx:258: characters 5-41 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
source/LuaClass.hx:42: characters 56-58 : Abstract haxe.ds.Map has no @:to function that accepts haxe.IMap<Any, LuaClass>

how do i fix it?

**Comment by jukru89** [comment]
Oh wait I figured it out

**Comment by silvashp** [comment]
how did you figure it out
