### ISSUE TITLE
Enhancement: If your having problems with the shaders

### ISSUE THREAD

**Issue by McJonnycat** [nebulazorua/andromeda-engine#88]
if your having problems with the shaders on mac or linux and such. Then use this [flxshader-fix](https://github.com/McJonnycat/Flxshader-fix) this will fix the shaders and i put a tutorial on the bottom to see how to add it on there. @nebulazorua i am not trying to self promote in your repository i am only trying to help people if the shaders are crashing. @nebulazorua if you want to you can take this down i am just trying to help people

**Comment by McJonnycat** [comment]
and if your also having fps issues with it being a bit laggy just do lime build [your platform] -debug and it will cause less lag issue i hope you guys have a good day.

**Comment by nebulazorua** [comment]
this.. doesnt fix anything tho?
All it does is let you use them at compile-time iirc, and I'll be adding @gedehari's one at some point

**Comment by McJonnycat** [comment]
gedeharis's shader? will it work for the shaders that you ported
