### ISSUE TITLE
Bug Report: Low framerate while playing a song

### ISSUE THREAD

**Issue by Stilic** [nebulazorua/andromeda-engine#93]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
**Windows 11**

## What version of the game are you using? Look in the bottom left corner of the main menu.
**The latest version**

-----

While I play a song, the FPS fall to 50. I am on a PC with a Intel I5 (integrated graphics card) and 8 GB of RAM. I have also a laptop with very similar specs and with 16 GB of RAM (and a SSD but IDK if this information is userful).

**Comment by Stilic** [comment]
i will provide images when i am at home btw

**Comment by nebulazorua** [comment]
Which chart are you playing

**Comment by Stilic** [comment]
The normal Bopeebo chart.

**Comment by Stilic** [comment]
On the latest commit:
![image](https://user-images.githubusercontent.com/63605602/161400424-ec950a2b-ec76-49b3-9f68-7984597d7807.png)

On the latest release downloaded from the GitHub "Releases" tab:
![image](https://user-images.githubusercontent.com/63605602/161400471-521dcda9-d3fa-41aa-8645-ca4d2d6d524e.png)

**Comment by Stilic** [comment]
@nebulazorua I am gonna try to fix that in the next week, if I have time and don't forgot.

**Comment by nebulazorua** [comment]
aight if you wanna
I've been working on mods and optimizations in said mods
These will come to base andromeda at some point when I'm not busy

**Comment by Stilic** [comment]
I discovered that the lags were caused by the raymarching shader. Disabling the shader fix them.

**Comment by Stilic** [comment]
ok sorry but i didn't find a optimized raymarching shader. i will try to do that in the next two weeks maybe.
